### ISSUE TITLE
PatchCallback Signature

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge-repo#105]
In `automerge` the `PatchCallback` has been recently updated so that the `PatchInfo` parameter includes a `source` property.

At the moment, the patch information is returned to the user as below:

https://github.com/automerge/automerge-repo/blob/b48a3db6a87942398290bcb69a216680fd2f31ae/packages/automerge-repo/src/DocHandle.ts#L42

Can I propose that we adopt a similar signature to that of the `PatchCallback`?

```ts
const doc = A.init<T>({
  patchCallback: (patches, pathInfo) =>
    this.emit("patch", { handle: this, patches, patchInfo }),
})
```

**Comment by acurrieclark** [comment]
This is, of course, breaking, but the alternative would be to add a new property each time the automerge `PatchInfo` is added to.

**Comment by pvh** [comment]
I agree being consistent is important and we're pre 1.0 so let's just do it and make sure it pops up in the release notes. Anyone using Typescript should be okay at least :)
