### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexjg** [automerge/automerge-repo#117]
Currently the sole form of documentation is the typescript types. This is not nothing but we need more. To start I think we need:

1. Typedoc comments on all the public methods (unless the name of the method is descriptive enough). 
2. A more "how to use this" style guide

Once the typedoc comments are complete we can publish them on the automerge.org from https://github.com/automerge/automerge.github.io, we already do this for `automerge` so it will hopefully be easy to add.

The source of the "how to" guide for automerge is entirely within https://github.com/automerge/automerge.github.io so maybe we should also write the automerge-repo how to guide there?

- [ ] TypeDocs for Repo/DocCollection/Handle (others?)
- [ ] Updated examples on automerge.org
- [ ] READMEs of automerge-repo root
- [ ] README automerge-repo-sync-server
- [ ] READMEs of all example code
- [ ] Check comments in examples
- [ ] Check comments elsewhere in code
- [ ] get Automerge-Repo into Docusaurus on Automerge.org

**Comment by pvh** [comment]
This isn't strictly true; there's also the READMEs and the demo code. Those could all be better organized though.

**Comment by pvh** [comment]
I'm feeling pretty good about this. I think having an omnibus ticket here is now redundant and future improvements should get their own issues. Closing this out.
