### ISSUE TITLE
1.0 Release

### ISSUE THREAD

**Issue by alexjg** [automerge/automerge-repo#118]
This is a meta issue tracking the things we need to do prior to release

- [x] #116 
- [x] #115 
- [x] #108 
- [x] #117 
- [ ] #119 
- [x] #120 
- [x] #122 
- [x] #138 

For consideration:
- [x] #127 
- [x] #126
- [x] #50
- [x] #129

**Comment by pvh** [comment]
Make sure all demo code is updated & clean

**Comment by pvh** [comment]
Move demos & sync server out of /packages

**Comment by pvh** [comment]
Doc / value() name alignment

**Comment by pvh** [comment]
pureJS demo?

**Comment by pvh** [comment]
mergeText()?

**Comment by pvh** [comment]
BroadcastChannel breaks ephemeral data with >2 clients

**Comment by alexjg** [comment]
For anyone following along PVH's comments above are a list of things we talked about synchronously as being important for a release. I've created issues for most of them and added them to the tracking issue. With the exception of 

* `mergeText`
* change/patch confusiong
* BroadcastChannel breaks ephemeral data

I think these can all be fixed in a backwards compatible manner  and are low enough priority that we shouldn't block a release on them.

**Comment by alexjg** [comment]
One question is whether we should block this release on #32. I think @acurrieclark presents a good argument in that issue that we should redesign our message types. We already have interoperable implementations in various states in Rust, Swift, and Kotlin. It would be nice if we could standardise our wire protocol before even more implementations pop up.

On the other hand, I want to get this release out fairly soon and this _might_ be the kind of design task that expands surprisigngly. Maybe we should just add a version negotiation step so that we can solve this later? The tradeoff obviously being that then we might end up supporting the current protocol as a legacy protocol for a while? @pvh @HerbCaudill thoughts?

**Comment by pvh** [comment]
So, sorry it took a bit to get back to you. I think this list is roughly correct. I would like to land @neftaly 's work on useAwareness and useBootstrap in here as well, but agree we should not block. I wanted to deal with 87 pre-1.0 but I feel at this point that it's not far enough along to commit to and just *barely* shy of being worth blocking a release (mostly due to uncertainty about what to do).

**Comment by neftaly** [comment]
#45 is blocked by #112 

@pvh has taken over #102 and I think is also blocked by #112

**Comment by pvh** [comment]
#102 and #112 are now landed on main -- happy to try and get #45 landed too.

**Comment by pvh** [comment]
Since @neftaly asked, the goal is to finish this list for a release in two weeks. That means ideally clearing the list out *this* week and then spending the following week fixing bugs / polishing / etc.

**Comment by pvh** [comment]
Okay -- there are PRs up for all of these now in one form or another except #116. @alexjg would love your review of the small stuff; feel free to land where you're confident. I'm going to call it a night here.

**Comment by acurrieclark** [comment]
@alexjg Added a few issues for consideration for v1 following conversations with @pvh

**Comment by neftaly** [comment]
I suggest fixing #129 for 1.0

**Comment by acurrieclark** [comment]
@alexjg i think we could probably close this out?
