### ISSUE TITLE
Control sharing on a per document level

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge-repo#19]
I had a conversation with @pvh last week about how it would be best to go about managing which documents in a repo are permitted to be shared with which peers. At the moment, there is a `sharePolicy` option which takes a `peerId` parameter, but this only determines whether or not a peer should be shared with at all.

It seems to me that whether or not a document should be shared with peers depends on factors which may or may not be in Automerge's control or purview. As such, it makes sense to me to take control of that outside of `automerge-repo` and allow a user to permit or deny based on their own criteria.

I would love to put together a PR for this, but wanted to discuss a possible API for this before continuing. My preferred route right now would be:

- Pass a callback as an additional option which takes both a `peerId` and a `documentId`. This would then be called any time a peer or a document is added to determine whether or not it should be shared. 
- While the current `sharePolicy` is set when the peer is added (the callback is evaluated once only), this new callback would be executed each time a new peer joined or a document was added.

I am sure there are other methods I have not considered, and would be grateful for peoples' thoughts on the subject.

**Comment by acurrieclark** [comment]
Been doing some more thinking about this, and I think it could pretty much replace the current `sharePolicy` implementation.

 I’m going to start by writing some `CollectionSynchronizer` tests to ensure the current behaviour persists then I’ll adapt how the callback is passed through the classes.

**Comment by HerbCaudill** [comment]
closed by #21
