### ISSUE TITLE
Wrong peerMetadata Sent on Message receive in BroadcastChannel adapter

### ISSUE THREAD

**Issue by justin0mcateer** [automerge/automerge-repo#270]
https://github.com/automerge/automerge-repo/blob/main/packages/automerge-repo-network-broadcastchannel/src/index.ts#L60

The 'peer-candidate' event is emitted with the peerMetadata of the _local_ Peer, NOT the metadata of the peer we received the message from.

This doesn't make sense and is different from the 'MessageChannel' implementation for example.

**Comment by acurrieclark** [comment]
Is the `senderId` in this context not the one received in the message? If so, it is indeed from the new peer.

**Comment by justin0mcateer** [comment]
senderId is unpacked from the received message in the message handler here:
`const { senderId, type } = message`

The peerMetadata value is closed over from the call to 'connect' which receives the local peerMetadata from the NetworkSubsystem.

**Comment by acurrieclark** [comment]
My apologies, I didn’t read your issue correctly at all. You are indeed correct.

Are you in a position to put in a PR?

**Comment by acurrieclark** [comment]
Fixed by #287
