### ISSUE TITLE
Virus detected in github head! Windows Defender Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by alienself** [automerge/automerge-repo#308]
Hi team, 

It seems like a virus is present in the automerge-repo! 
When downloading the repo as zip, chrome immediately blocks the files and Windows defender reports a Trojan:Script/Wacatac.H!ml in the repo's head..

![Screenshot 2024-03-09 152644](https://github.com/automerge/automerge-repo/assets/87069099/97b8e3f7-fc50-4ed4-9ced-552736051594)

**Comment by heckj** [comment]
I downloaded the zip file from `main` as well as the latest release, and no there was no virus included in any of that content that I downloaded directly from GitHub. Did you download through another site or mechanism?

**Comment by alienself** [comment]
Hm strange! Yes directly from Github, I am using windows 11 / latest chrome.

**Comment by heckj** [comment]
I suspect there's something awry with your local environment...

**Comment by cristianmadularu** [comment]
I am using Windows 11 and latest Chrome and I do not see this. Maybe you have some security policy or scanner set by the IT dep.?
