### ISSUE TITLE
When a change event is emitted by the handle the `handle.docSync()` is still the old value

### ISSUE THREAD

**Issue by pvh** [automerge/automerge-repo#338]
This is fine if you're dealing with the doc directly in your callback but a pain in the neck if you're triggering a bunch of other code.

Should be straightforward to resequence this but I just wanted to record the note.

**Comment by pvh** [comment]
@HerbCaudill this might be real obvious to you how to fix ... good motivation for me to land the new xstate PR too :)

**Comment by HerbCaudill** [comment]
@pvh I can't reproduce this. This test passes: 

```ts
  it("docSync should return the changed doc when called in the change event listener", async () => {
    const handle = new DocHandle<TestDoc>(TEST_ID, { isNew: true })
    const p = eventPromise(handle, "change")
    handle.change(doc => {
      doc.foo = "bar"
    })
    const expected = { foo: "bar" }
    await p.then(({ doc }) => {
      assert.deepEqual(doc, expected)
      assert.deepEqual(handle.docSync(), expected)
    })
    assert.deepEqual(handle.docSync(), expected)
  })
```

**Comment by HerbCaudill** [comment]
For that matter, this test passes: 

```ts
  it("docSync should return the changed doc when called in the change event listener", async () => {
    const handle = new DocHandle<TestDoc>(TEST_ID, { isNew: true })
    handle.change(doc => {
      doc.foo = "bar"
    })
    assert.deepEqual(handle.docSync(), { foo: "bar" })
  })
```

**Comment by acurrieclark** [comment]
This test should already cover this too:
https://github.com/automerge/automerge-repo/blob/718b3a3fcc751eda6fd52e7e863904effcecd13a/packages/automerge-repo/test/DocHandle.test.ts#L174

**Comment by pvh** [comment]
I thought we'd fixed this at some point in the past as well, but I definitely saw this behaviour in my prototype. I'll investigate further. This was in the midst of things Getting Very Weird as I entered a feedback loop of edits.

**Comment by pvh** [comment]
Just closing this out because I haven't been able to reproduce. I'm going to chock this one up to operator error.
