### ISSUE TITLE
repo.clone error message suggests using "handle.waitForReady", which doesn't exist

### ISSUE THREAD

**Issue by joshuahhh** [automerge/automerge-repo#354]
See here:

https://github.com/automerge/automerge-repo/blob/caf338c97d8c2c669870e3d3efc34e0eabf3ca60/packages/automerge-repo/src/Repo.ts#L391-L397

I'm not sure what the preferred alternative is.

**Comment by pvh** [comment]
`whenReady()`. fixed and will go in the next release.
