### ISSUE TITLE
Add a way to properly close and cleanup automerge-repo

### ISSUE THREAD

**Issue by nikgraf** [automerge/automerge-repo#357]
Use-case: User logs out of the application

I think there are actually two different use-cases:
- user logs out of the server, but keeps local data. In this case just the network adapters should not try to reconnect. Currently it tries to reconnect based on the `retryInterval`
- user logs out of the server and wants to delete all local data. In this case disconnect from the network adapters and clean up the storage layers

What I tried:

```ts
export const cleanup = () => {
  // disconnect the previous websocket connection
  if (browserWebSocketClientAdapter) {
    browserWebSocketClientAdapter.disconnect();
    browserWebSocketClientAdapter.socket?.close();
  }

  if (repo) {
    repo = undefined;
  }

  indexedDB.deleteDatabase("automerge");
};
```

Current workaround: I remove the automerge databased and do a hard-reload of the page.

**Comment by pvh** [comment]
This would be a great feature and we should absolutely support this properly. I see several separate use cases: 
 * going offline
 * shutting down cleanly
 * logging out / deleting local data

For going offline, we really just need the network subsystem to have a bit of cleanup work. I'd be happy to pair on this some time as I think it's mostly a matter of writing a few simple APIs and clearing things up. There are heaps of usecases for this, particularly for demo and testing code, but also as we start to flesh out support for having multiple simultaneous sync servers.

In the case of clean shutdown there's an obvious need here for CLI apps. You make a document and you want to know it's synced before closing (or you fetch one!). Thanks to some help from DXOS we have some progress on flushing to disk but these APIs could definitely be further iterated. We do not, should not, and must not ever rely on this behaviour: computers can crash at any time for any reason!

Finally, I think the case you're describing here for cleaning up localStorage makes perfect sense. This is an easy API to add to the StorageAdapter and obviously we want to be a little careful with how it's implemented. Some things to consider: if a user has local-only data should we make sure we can tell if it's synced before deleting things locally? What about "account deletion" where a user might want to remove all their own data (but not things held by other users). 

This feels like an important (and so far underconsidered) aspect of the design of this system and I'd welcome any help with all of it.

**Comment by pvh** [comment]
@nikgraf I believe this is now finished in the automerge-repo 2.0.0-alpha release! you can call repo.shutdown() for a clean shutdown.

one thing to be aware of is that this doesn't have the option (yet) to block on ensuring all documents are synced but it does do a clean shutdown of the network adapters and flush to disk.

**Comment by pvh** [comment]
PS, while i'm hesitant to add a deleteEverything() method to the storage API, i believe removeRange with the prefix [] would have the same effect in a cross-storage-adapter way.
