### ISSUE TITLE
Improve incremental data storage by using hashes as keys instead of integers

### ISSUE THREAD

**Issue by pvh** [automerge/automerge-repo#49]
The current implementation of the Storage Subsystem writes an extra file for each individual change. These files are identified as `$docId.incremental.$number`. This works *okay* if you have only a small number of incremental changes and only a single writer.

We could do better, I think, in two ways. For a storage engine that supports locking and append operations, we could simply append the change onto the end of the document. Automerge is capable of reading additional changes this way (and indeed, this is how we assemble a document at load time.)

For key value engines that don't allow edits, we could store the incremental edits at `$docId/incremental/$hashOfChange`. This would allow for a few nice properties. First, we don't have to worry about race conditions in writing (as much). If two agents both write an incremental change, no big deal! (When we go to clean up these incremental keys we should be careful not to delete all keys: more may have arrived from another process while we were working: just delete keys you can guarantee you've got in your current snapshot. You will also need to take a lock while making a snapshot so you don't have two nodes each trying to write a snapshot with disjoint data.)

The cost of this approach is that it will require the storage engines to be able to enumerate all the keys in a sub-namespace. For a filesystem, this is pretty trivial: put the incremental keys in a subdirectory. Other databases will have similar properties. The one place I'm not sure we know how to support with this approach (but that I think we should support) is an S3 backend.

If anyone wants to tinker with this, please feel free to grab me and ask any clarifying questions. Otherwise I'll get around to it at some point, I'm sure.

**Comment by acurrieclark** [comment]
Closed by #115
