### ISSUE TITLE
Implementation of `DocSynchronizer.receiveSyncMessage` may cause messages to be received out of order

### ISSUE THREAD

**Issue by ecstatic-morse** [automerge/automerge-repo#70]
While writing #69 , I noticed that `receiveSyncMessage` waits for the doc handle to be ready before calling `update`

https://github.com/automerge/automerge-repo/blob/ee508301f84339cad316bd4fb68216397c72bd51/packages/automerge-repo/src/synchronizer/DocSynchronizer.ts#L135-L160

`receiveSyncMessage` is invoked (indirectly through `CollectionSynchronizer`) in an `on("message", ...)` listener in `Repo.ts`:

https://github.com/automerge/automerge-repo/blob/ee508301f84339cad316bd4fb68216397c72bd51/packages/automerge-repo/src/Repo.ts#L98-L112

However, if we get two messages before doc handle is ready, I don't think there's any guarantee that the two listeners will resume from the `await` in the same order they reached it, which could cause sync messages to be processed out of order. I haven't reproduced this yet, so maybe I'm wrong about the spec and someone can correct me.

**Comment by acurrieclark** [comment]
I'm pretty certain this has been closed by the work in #71, so closing for now.
