### ISSUE TITLE
`NetworkSubsystem` Review

### ISSUE THREAD

**Issue by acurrieclark** [automerge/automerge-repo#87]
I have spent some time considering the current `NetworkSubsystem` and `NetworkAdapter` implementations and I think it's worth starting a discussion on reviewing and simplifying. I admit this is pretty opinionated, but I am not tied to any of these thoughts with any enormous force.

Most of this came from thinking about 2 steps:

1. Allowing multiple message types to be passed between peers
2. Simplifying the Adapter Interface to make implementing new adapters more straightforward

**ChannelId**
TLDR. I think we should lose/replace it.

The `ChannelId` (to the best of my understanding) is used in 3 ways. The first is as some kind of ID when we ask the network system and subsequently each adapter to join a "channel". This is done when the [system is set up for the first time](https://github.com/automerge/automerge-repo/blob/4fce1a0a11c6482c078b0d4750c4123d9d9a72e3/packages/automerge-repo/src/Repo.ts#L116). We join a `SYNC_CHANNEL` channel, then there is never another channel joined, and the `SYNC_CHANNEL` is never referred to again. **The ID in this case is redundant**.

The second is to identify which document is being synced when sync messages are being passed between peers. I think we would be **better to just use `DocumentId`s in this case**, and update the `NetworkAdapter` API to match.

The third is to identify if a message is meant for broadcast, if it is ephemeral. In this case the `ChannelId` is prefixed with `m/` as a way to differentiate it from other message types. I think a clearer way forward would be to specify the message type explicitly as `ephemeral`.

**Join**
At the moment, this is called when the network subsystem is set up, for any channels which are joined. However, when the subsytem is initialised, there are no channels, so nothing is joined. The only time we join is when the repo is initialised for the first time, at the [top level of the constructor](https://github.com/automerge/automerge-repo/blob/4fce1a0a11c6482c078b0d4750c4123d9d9a72e3/packages/automerge-repo/src/Repo.ts#L116). I think we could likely do away with `join` on both the subsystem and the adapter level; when an adapter is initialised, it should run whatever is needed to `join` automatically. The only reason to hang on to it would be in the case that the `leave` method is actually useful.

**Leave**
As far as I can tell, the `leave` method in the `NetworkSubsystem` is never called. Do we need to actually stop a network adapter? At the moment the suggestion is that we can either leave all adapters (channels, right now) but not individual ones. I can see a world where you might want to be able to stop syncing to a server, for example, but keep syncing between local tabs in your browser/app.

**Adapters**
At its simplest, a network adapter needs to be able to tell repo when:
- It opens
- It has a peer candidate
- It loses a peer
- It has a message from one of those peers
- It closes

It also needs to be able to send messages to those peers.

All of these events currently exist on `NetworkAdapter`, but at no point is `open` fired by any of the existing adapters. If it did, I think we could bring all of those event types `in house`. For example:

1. An adapter sets itself up, and emits an `open` event.
2. The subsystem sends out a `peer-candidate` message type (discussed further below), announcing itself to the network.
3. Any peers receiving the message log the `PeerId`, announce the connection to the `DocSynchronizer` and reply with their own `peer-candidate` message.

I might be underestimating some of the specificity of the initial handshakes required here, but it strikes me that essentially each adapter needs to set up and configure the network, then pass messages between instances of `Repo` on one peer, with another.

**Messages**
So, to messages. I think we should essentially add message types. Off the top of my head, they would be:

`peer-candidate`: Sent by a peer when an adapter opens a network connection, or when a new peer connects.
`peer-disconnected`: Sent by a peer when it wants to let other peers know that it no longer wants to be a peer, but the network is still active
`sync-message`: exchanging sync messages between peers
`ephemeral`: sending broadcast messages to all peers
`auth`: authentication messages (to fit in with @HerbCaudill's work)
`document-not-found`: explicit response to a sync request on a document which a peer does not have, and cannot be found

There may be more here, but the point is that I think that all of these messages could/should be handled by the subsystem, so that the Adapters can be left to set up the network, and then just communicate.

Would love to hear thoughts and corrections on the above. If there is anything I have misunderstood, please don't hesitate to point out

**Comment by pvh** [comment]
The issue with that is what the "recipientId" is, then. I tried setting it to a faux "*" recipient for a while but that led to problems with deciding who to rebroadcast to. I think it's important to think a bit about what the promises of the network layer need to be: what kinds of guarantees do we assume? In-order delivery?
