### ISSUE TITLE
Thoughts on architecture

### ISSUE THREAD

**Issue by HerbCaudill** [automerge/automerge-repo#88]
Peter's aspiration is for this library to provide composable units that can be used independently, or swapped out for alternative implementations. 

I'm on board with that aspiration in principle. Clearly the `NetworkAdapter` and `StorageAdapter` abstractions make a ton of sense, as does the proposed `AuthProvider`. 

But I still can't picture what it would mean to use `DocCollection`, `NetworkSubsystem`, `EphemeralData`, or `StorageSubsystem` independently of `Repo`, or what the motivation would be. 

In the meantime, we're paying a steep cognitive price for what feels to me like premature abstraction. The work that automerge-repo is doing is not all _that_ complex, but it's hard to see what's actually load-bearing through the maze of event-driven orchestration between all these classes. All this indirection means that takes work to track down who depends on what, what an event is intended to accomplish, and what's part of the public API vs internal only. 

I'd like to do one of two things: 

1. document and test ways in which the current decomposition would be useful to someone; OR
2. fold some or all of those classes into `Repo` 

My preference would be to go ahead and do (2). We can always refactor later to reintroduce some abstraction if and when we have an actual use case for it, and in the meantime we'll just be able to see the shape of the thing more clearly.

**Comment by acurrieclark** [comment]
This pretty much echoes my thoughts on the topic. It would make perfect sense to me to fold `DocCollection` in to `Repo`, for example.

I am personally a fan of having _some_ abstraction to maintain some separation of concerns, but if there were clear ways to simplify the architecture by removing it, I'm all for it. Especially if it might encourage more people to get involved and contribute.

**Comment by acurrieclark** [comment]
@HerbCaudill do you think we are pretty much as far down this line as we need to go for now? I was thinking this could be closed, but happy to leave it open if you think there is work outstanding.

**Comment by HerbCaudill** [comment]
Sorry, just noticed this! Yep, I'll close.
